import { icon } from './icons.mjs';
import { flowNodes, renderWorkflow } from './workflow.mjs';
import { renderPoseidon, renderPoseidonInspector } from './poseidon.mjs';

const app = document.querySelector('#app');
const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const tabs = {
  poseidon:{name:'Poseidon',icon:'poseidon'},
  workflow:{name:'Delivery review',icon:'branch'}, brief:{name:'Weekly brief',icon:'document'},
  notes:{name:'Working notes',icon:'code'}, agents:{name:'Agents',icon:'agent'}, sources:{name:'Sources',icon:'library'}, overview:{name:'Workspace',icon:'grid'}
};
const initialTab = Object.hasOwn(tabs, location.hash.slice(1)) ? location.hash.slice(1) : 'poseidon';
const sectionFor = id => ['poseidon','agents','sources'].includes(id) ? id : 'work';
const agents = [
  {id:'research',name:'Research',icon:'fish',description:'Find the evidence. Connect the records. Keep the open questions visible.',task:'Read and reconcile selected sources.',access:'Read selected sources; write draft findings.'},
  {id:'analysis',name:'Delivery analysis',icon:'squid',description:'Bring plans and delivery records into a view the team can examine.',task:'Compare progress, blockers and decisions.',access:'Read selected sources; write draft analysis.'},
  {id:'review',name:'Review',icon:'turtle',description:'Check claims against their evidence and prepare the work for a person to review.',task:'Check that each claim has a source.',access:'Read drafts and sources; propose revisions.'}
];
const sources = [
  {name:'Delivery register',type:'Table',icon:'database',detail:'Example project records',body:'Onboarding workstream\n\nThree actions complete.\nSource-data import blocked: field mapping awaiting agreement.\nDelivery date: to be confirmed.'},
  {name:'Working notes',type:'Document',icon:'document',detail:'Latest project review',body:'Test the import once the mapping is agreed.\n\nThe team will revisit the delivery date after that test.\nThe current record does not support a revised date.'},
  {name:'Decision log',type:'Document',icon:'document',detail:'Open decisions',body:'Mapping decision\n\nDecision owner: unassigned.\nNext step: project lead to confirm ownership.\nStatus: open.'}
];
const state = {
  active:initialTab,open:[...new Set([initialTab,'workflow','brief'])],sidebar:innerWidth>760,inspector:innerWidth>=1380,activity:false,
  poseidon:{task:'research',priority:'balanced',budget:'standard',previewed:false},
  selectedNode:'research',section:sectionFor(initialTab),project:'Operations',zoom:1,selectedAgent:'research',selectedSource:0,
  notes:'# Working notes\n\n## The question\nWhat has changed in delivery this week?\n\n## Sources to check\n- Delivery register\n- Working notes\n- Decision log\n\n## Open decisions\nConfirm who owns the source-data mapping.\n',
  instructions:{research:'Read only the selected sources. Attach evidence to each finding. Keep missing information and contradictory records visible.',analysis:'Compare the delivery records and plans. Identify changes, blockers and open decisions. Attach the source behind each observation.',review:'Check each claim against its source. Flag unsupported conclusions and unresolved questions for human review.'},
  activityTab:'activity',preview:false,previewStep:0,approved:false,dirty:false,customTabs:{},density:'Comfortable'
};
try { const saved=JSON.parse(localStorage.getItem('koralli-workspace-layout')||'null');if(saved){if(['Comfortable','Compact'].includes(saved.density))state.density=saved.density;} } catch {}
let previewTimer;
let toastTimer;
const button = (name,label,action,extra='') => `<button class="icon-button" data-action="${action}" aria-label="${label}" title="${label}" ${extra}>${icon(name)}</button>`;
const metadata = id => tabs[id] || state.customTabs[id];
function notify(message){clearTimeout(toastTimer);const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('visible');toastTimer=setTimeout(()=>toast.classList.remove('visible'),2800);}
function preference(){try{localStorage.setItem('koralli-workspace-layout',JSON.stringify({density:state.density}));}catch{}}
function openTab(id){if(!metadata(id))return;if(!state.open.includes(id))state.open.push(id);state.active=id;if(id!=='workflow'){clearTimeout(previewTimer);state.preview=false;}state.section=sectionFor(id);history.replaceState(null,'','#'+id);if(innerWidth<=760)state.sidebar=false;render();app.querySelector('.work-surface').scrollTop=0;}
function closeTab(id){const wasActive=state.active===id;const at=state.open.indexOf(id);state.open=state.open.filter(tab=>tab!==id);if(wasActive)state.active=state.open[Math.max(0,at-1)]||'overview';if(!state.open.length)state.open=['overview'];state.section=sectionFor(state.active);history.replaceState(null,'','#'+state.active);if(state.active!=='workflow'){clearTimeout(previewTimer);state.preview=false;}render();if(wasActive)app.querySelector('.work-surface').scrollTop=0;}

function renderSidebar(){
  return `<aside class="explorer" aria-label="Workspace explorer"><div class="explorer-heading"><span class="mono">EXPLORER</span>${button('plus','New work','new')}</div>
    <button class="workspace-picker" data-action="switch-project">${icon('layers',19)}<span>${state.project}<small>Personal workspace</small></span>${icon('chevronDown',14)}</button>
    <div class="explorer-group"><div class="explorer-group-label mono">ORCHESTRATION</div><button class="tree-item ${state.active==='poseidon'?'active':''}" data-tab="poseidon">${icon('poseidon',19)}<span>Poseidon</span><i class="hollow-dot"></i></button></div>
    <div class="explorer-group"><div class="explorer-group-label mono">WORKSPACES <span>01</span></div><button class="tree-parent selected" data-tab="workflow">${icon('chevronDown',12)}${icon('folder',16)}<span>Delivery review</span></button><div class="tree-children">${[['workflow','branch','Workflow'],['brief','document','Weekly brief'],['notes','code','Working notes']].map(([id,shape,name])=>`<button class="tree-item ${state.active===id?'active':''}" data-tab="${id}">${icon(shape,16)}<span>${name}</span>${id==='notes'&&state.dirty?'<i class="unsaved-dot"></i>':''}</button>`).join('')}</div></div>
    <div class="explorer-group"><div class="explorer-group-label mono">AGENTS <button data-tab="agents" aria-label="Browse agents">${icon('arrowRight',13)}</button></div>${agents.map(a=>`<button class="tree-item" data-agent="${a.id}">${icon(a.icon,17)}<span>${a.name}</span><i class="hollow-dot"></i></button>`).join('')}</div>
    <div class="explorer-group"><div class="explorer-group-label mono">CONTEXT <button data-tab="sources" aria-label="Browse sources">${icon('plus',13)}</button></div>${sources.map((source,i)=>`<button class="tree-item" data-source="${i}">${icon(source.icon,16)}<span>${source.name}</span></button>`).join('')}</div>
    <div class="explorer-bottom"><img class="explorer-coral" src="./assets/coral-network.svg" width="170" height="79" alt=""><p>Different strengths.<br>Shared purpose.</p><span class="mono">KORALLI WORKSPACE / 0.1</span></div></aside>`;
}
function renderBrief(){return `<article class="document-view"><div class="document-top"><span class="eyebrow">DELIVERY / WEEKLY BRIEF</span><button class="text-button" data-action="export">${icon('external',14)} Export</button></div><div class="document-title"><h1>A clearer picture<br>of the week.</h1><p>Prepared from three selected sources.<br>Example brief for human review.</p></div><div class="document-meta"><span>${icon('clock',14)} ${state.approved?'Reviewed draft':'Draft · awaiting review'}</span><span>Project lead</span></div>
    <section class="document-section"><span class="section-number mono">01</span><div><h2>What moved forward</h2><p>Three onboarding actions are complete. The source-data import remains blocked by an unresolved field mapping. <button class="reference" data-source="0" aria-label="Open delivery register source">[1]</button></p></div></section>
    <section class="document-section"><span class="section-number mono">02</span><div><h2>What remains open</h2><p>The team plans to test the import after the mapping is agreed. The records do not establish a revised delivery date. <button class="reference" data-source="1" aria-label="Open working notes source">[2]</button></p></div></section>
    <section class="document-section"><span class="section-number mono coral">03</span><div><h2>A decision for the team</h2><p>Confirm who owns the mapping decision. This is currently unassigned in the decision log. <button class="reference" data-source="2" aria-label="Open decision log source">[3]</button></p></div></section>
    <div class="document-actions"><button class="primary-button" data-action="approve" ${state.approved?'disabled':''}>${icon('check',15)}${state.approved?'Draft approved':'Approve draft'}</button><button class="secondary-button" data-tab="notes">Add a review note ${icon('arrowRight',14)}</button></div></article>`;}
function renderAgents(){return `<section class="library-view"><div class="view-heading"><p class="eyebrow">AGENT LIBRARY</p><h1>Specialists around the work.</h1><p>Give each agent a clear role, useful tools and a defined scope.</p></div><div class="library-section-label mono"><span>NAME / RESPONSIBILITY</span><span>CONFIGURATION</span></div>${agents.map((agent,i)=>`<button class="agent-row ${state.selectedAgent===agent.id?'selected':''}" data-agent="${agent.id}"><span class="agent-drawing">${icon(agent.icon,38)}</span><span><span class="mono agent-index">0${i+1} / AGENT TEMPLATE</span><strong>${agent.name}</strong><span class="row-description">${agent.description}</span></span><span class="agent-row-tail">Draft ${icon('arrowRight',17)}</span></button>`).join('')}<p class="view-note">Select an agent to edit its instructions and inspect its access.</p></section>`;}
function renderSources(){const source=sources[state.selectedSource];return `<section class="library-view"><div class="view-heading"><p class="eyebrow">WORKSPACE CONTEXT</p><h1>Start with what you know.</h1><p>The records, documents and definitions available to this work.</p></div><div class="source-table"><div class="source-table-head mono"><span>SOURCE</span><span>TYPE</span><span>ACCESS</span></div>${sources.map((item,i)=>`<button class="source-row ${state.selectedSource===i?'selected':''}" data-source="${i}"><span>${icon(item.icon,19)}<span>${item.name}<small>${item.detail}</small></span></span><span>${item.type}</span><span>Read only</span></button>`).join('')}</div><div class="source-preview"><p class="eyebrow">SELECTED SOURCE / EXAMPLE CONTENT</p><h2>${source.name}</h2><pre>${escape(source.body)}</pre></div></section>`;}
function renderNotes(){return `<section class="notes-view"><div class="notes-toolbar"><span class="mono">MARKDOWN</span><span data-note-status>${state.dirty?'Edited in this session':'Example working notes'}</span><button class="text-button" data-action="export">${icon('external',14)} Export</button></div><label class="sr-only" for="notes-editor">Working notes</label><textarea id="notes-editor" spellcheck="false">${escape(state.notes)}</textarea><footer class="editor-footer"><span>Plain text · editable locally</span><span data-word-count>${state.notes.trim().split(/\s+/).length} words</span></footer></section>`;}
function renderOverview(){return `<section class="overview-view"><p class="eyebrow">KORALLI / ${state.project.toUpperCase()}</p><h1>A place for<br>work to take shape.</h1><p>Bring a question, assemble the context and give the work a direction.</p><button class="primary-button" data-action="new">${icon('plus',16)} New work</button><div class="overview-recent"><p class="eyebrow">CONTINUE WORKING</p><button data-tab="workflow">${icon('branch',23)}<span><strong>Delivery review</strong><small>Research, analysis and human review</small></span>${icon('arrowRight',19)}</button><button data-tab="brief">${icon('document',23)}<span><strong>Weekly brief</strong><small>Example document · draft</small></span>${icon('arrowRight',19)}</button></div></section>`;}
function renderCustom(){const data=metadata(state.active);return `<section class="overview-view"><p class="eyebrow">NEW WORKSPACE</p><h1>${escape(data.name)}</h1><p>Your workspace is ready. Start from the example workflow to explore how the pieces fit together.</p><button class="primary-button" data-tab="workflow">${icon('branch',17)} Open workflow template</button></section>`;}
function renderContent(){switch(state.active){case'poseidon':return renderPoseidon(state.poseidon);case'workflow':return renderWorkflow(state);case'brief':return renderBrief();case'notes':return renderNotes();case'agents':return renderAgents();case'sources':return renderSources();case'overview':return renderOverview();default:return renderCustom();}}

function renderInspector(){
  if(state.active==='poseidon')return renderPoseidonInspector(state.poseidon);
  if(!['workflow','agents','sources','brief'].includes(state.active))return `<aside class="inspector" aria-label="Inspector"><div class="inspector-heading"><span class="mono">WORKSPACE DETAILS</span>${button('close','Close inspector','inspector')}</div><div class="inspector-body"><div class="inspector-identity"><span class="inspector-symbol">${icon(state.active==='notes'?'code':'folder',32)}</span><p class="eyebrow">${state.active==='notes'?'WORKING DOCUMENT':'LOCAL WORKSPACE'}</p><h2>${escape(metadata(state.active).name)}</h2></div><p class="inspector-description">${state.active==='notes'?'Keep questions, observations and decisions alongside the work. Export your notes to keep a copy.':'Bring the context, agents and outputs together around a question.'}</p><div class="inspector-block"><p class="eyebrow">STORAGE</p><p class="inspector-value">Edits are held in this preview session. Reloading restores the example.</p></div><button class="inspector-link" data-tab="workflow">Open delivery workflow ${icon('arrowRight',15)}</button><div class="inspector-note"><span class="hollow-dot"></span><p>Visual template.<br>No model or tools connected.</p></div></div></aside>`;
  const selectedAgent=agents.find(a=>a.id===state.selectedAgent);
  const selected=flowNodes.find(n=>n.id===state.selectedNode);
  const isAgent=state.active==='agents';
  const isSource=state.active==='sources';
  const title=isAgent?selectedAgent.name:isSource?sources[state.selectedSource].name:state.active==='brief'?'Document review':selected.title;
  const shape=isAgent?selectedAgent.icon:isSource?sources[state.selectedSource].icon:state.active==='brief'?'document':selected.icon;
  return `<aside class="inspector" aria-label="Inspector"><div class="inspector-heading"><span class="mono">${isAgent?'AGENT SETTINGS':isSource?'SOURCE DETAILS':'INSPECTOR'}</span>${button('close','Close inspector','inspector')}</div><div class="inspector-body"><div class="inspector-identity"><span class="inspector-symbol">${icon(shape,32)}</span><p class="eyebrow">${isAgent?'AGENT TEMPLATE':isSource?'WORKSPACE CONTEXT':state.active==='brief'?'REVIEW':'SELECTED STEP'}</p><h2>${title}</h2></div>
    <p class="inspector-description">${isAgent?selectedAgent.description:isSource?'Example material selected for this workflow. Original records stay unchanged.':state.active==='brief'?'Review the brief alongside its evidence. Keep unresolved questions visible.':selected.description}</p>
    <div class="inspector-block"><p class="eyebrow">${isAgent?'RESPONSIBILITY':'INPUTS'}</p>${isAgent?`<p class="inspector-value">${selectedAgent.task}</p>`:(isSource?['Sample content only']:(state.active==='brief'?['Draft brief','Three source references']:selected.inputs)).map(input=>`<div class="input-line">${icon('link',14)}<span>${input}</span></div>`).join('')}</div>
    ${isAgent?`<div class="inspector-block"><label class="eyebrow" for="agent-instructions">INSTRUCTIONS</label><textarea id="agent-instructions">${escape(state.instructions[state.selectedAgent])}</textarea><span class="field-note" data-instruction-status>Editable template instructions</span></div>`:`<div class="inspector-block"><p class="eyebrow">OUTPUT</p><p class="inspector-value">${isSource?'Source material with context':state.active==='brief'?'Reviewed weekly brief':selected.output}</p></div>`}
    <div class="inspector-block"><p class="eyebrow">ACCESS</p><p class="access-line">${icon('shield',16)} ${isAgent?selectedAgent.access:isSource?'Read only':state.active==='brief'?'Review and approve this draft':selected.access}</p></div>
    ${state.active==='workflow'?`<button class="inspector-link" ${['research','analysis'].includes(selected.id)?`data-agent="${selected.id}"`:`data-tab="${selected.id==='sources'?'sources':'brief'}"`}>${['output','review'].includes(selected.id)?'Open document':selected.id==='sources'?'Inspect sources':'Inspect agent template'}${icon('arrowRight',15)}</button>`:''}
    <div class="inspector-note"><span class="hollow-dot"></span><p>Visual template.<br>No model or tools connected.</p></div></div></aside>`;
}
function renderActivity(){return `<section class="activity-drawer" aria-label="Activity panel"><header><div class="drawer-tabs"><button class="${state.activityTab==='activity'?'active':''}" data-log="activity">Activity</button><button class="${state.activityTab==='outputs'?'active':''}" data-log="outputs">Outputs</button></div><span class="mono">${state.preview?'LOCAL PREVIEW':'WORKSPACE'}</span>${button('close','Close activity panel','activity')}</header><div class="activity-body">${state.activityTab==='outputs'?`<button class="output-row" data-tab="brief">${icon('document',17)}<span>Weekly brief</span><small>${state.approved?'Reviewed':'Example draft'}</small>${icon('arrowRight',14)}</button>`:`<div class="log-line"><span class="mono">TEMPLATE</span>${icon('check',13)}<p>Koralli Workspace template opened.</p></div><div class="log-line"><span class="mono">CONTEXT</span>${icon('library',13)}<p>Three example sources available for inspection.</p></div><div class="log-line"><span class="mono">${state.preview?'PREVIEW':'STATUS'}</span>${icon(state.preview?'play':'compass',13)}<p>${state.active==='poseidon'?(state.poseidon.previewed?'Illustrative route prepared. No model was called.':'Choose a task, priority and compute allowance to explore Poseidon.'):state.preview?'Showing the workflow sequence. No agent is running.':state.previewStep>=3?'Sequence preview complete. The review step is selected.':state.approved?'Example brief approved in this session.':'Ready to explore. Select a step to inspect its role.'}</p></div>`}</div></section>`;}

function render(){
  const previousScroll=app.querySelector('.work-surface')?.scrollTop||0;
  app.className=`workspace-app ${state.sidebar?'sidebar-open':''} ${state.inspector?'inspector-open':''} ${state.activity?'activity-open':''} ${state.preview?'is-previewing':''} ${state.density==='Compact'?'compact':''}`;
  app.innerHTML=`<header class="topbar"><a class="brand" href="#" data-tab="overview" aria-label="Koralli workspace home"><img src="./assets/coral-mark-header.webp" alt="" width="24" height="26"><span>koralli</span><span class="brand-divider"></span><small>workspace</small></a><button class="command-trigger" data-action="command" aria-label="Search workspace commands">${icon('search',14)}<span>Search or jump to…</span><kbd>⌘ K</kbd></button><div class="topbar-right"><span class="template-label">DESIGN PREVIEW</span>${button('sidebar','Toggle explorer · ⌘B','sidebar',`aria-expanded="${state.sidebar}"`)}${button('panel','Toggle inspector · ⌘.','inspector',`aria-expanded="${state.inspector}"`)}<button class="avatar" data-action="settings" aria-label="Workspace preferences">k.</button></div></header>
  <div class="app-body"><nav class="activity-rail" aria-label="Main navigation">${[['poseidon','poseidon','Poseidon orchestrator','poseidon'],['grid','work','Workspaces','overview'],['agent','agents','Agents','agents'],['library','sources','Sources','sources']].map(([shape,key,label,tab])=>`<button class="rail-button ${state.section===key?'active':''}" data-tab="${tab}" aria-label="${label}" title="${label}">${icon(shape,22)}</button>`).join('')}<span class="rail-spacer"></span>${button('activity','Toggle activity · ⌘J','activity',`aria-expanded="${state.activity}"`)}${button('settings','Preferences','settings')}</nav>
    ${state.sidebar?renderSidebar():''}
    <div class="workspace-centre"><div class="tabbar" role="tablist" aria-label="Open work">${state.open.map(id=>`<div class="tab-wrap ${state.active===id?'active':''}"><button id="tab-${id}" class="document-tab" role="tab" aria-selected="${state.active===id}" aria-controls="workspace-main" data-tab="${id}">${icon(metadata(id).icon,15)}<span>${escape(metadata(id).name)}</span></button><button class="tab-close" data-close-tab="${id}" aria-label="Close ${escape(metadata(id).name)}">${icon('close',12)}</button></div>`).join('')}<button class="new-tab" data-action="new" aria-label="New work">${icon('plus',16)}</button></div>
    <div class="workspace-toolbar"><div class="breadcrumbs"><span>${state.project}</span>${icon('chevron',11)}<span>${escape(metadata(state.active).name)}</span></div><div><span class="local-label"><i></i>Local</span>${state.active==='workflow'?`<button class="run-button" data-action="preview">${icon(state.preview?'pause':'play',13)}${state.preview?'Stop preview':'Preview sequence'}</button>`:''}</div></div>
    <main id="workspace-main" class="work-surface" role="tabpanel" aria-labelledby="tab-${state.active}" tabindex="-1">${renderContent()}</main>${state.activity?renderActivity():''}</div>
    ${state.inspector?renderInspector():''}</div>
    <footer class="statusbar"><div><span class="status-branch">${icon('branch',12)} koralli / template</span><span class="desktop-status">${icon('check',12)} All changes local</span></div><div><button data-action="command">${icon('command',12)} Commands</button><span>Example data</span><button data-action="activity">${icon('activity',13)} Activity</button></div></footer>`;
  if(app.querySelector('.work-surface'))app.querySelector('.work-surface').scrollTop=previousScroll;
}

function startPreview(){
  if(state.preview){clearTimeout(previewTimer);state.preview=false;render();return;}
  state.preview=true;state.previewStep=0;state.activity=true;state.selectedNode='sources';render();
  const sequence=['research','analysis','review'];
  function next(){if(!state.preview)return;state.selectedNode=sequence[state.previewStep];state.previewStep++;if(state.previewStep===sequence.length){state.preview=false;notify('Sequence preview complete. Nothing was executed.');}render();if(state.preview)previewTimer=setTimeout(next,900);}
  previewTimer=setTimeout(next,650);
}
const commands=[
  {name:'Open Poseidon orchestrator',hint:'Routing',icon:'poseidon',run:()=>openTab('poseidon')},
  {name:'Open delivery workflow',hint:'Workspace',icon:'branch',run:()=>openTab('workflow')},
  {name:'Open weekly brief',hint:'Document',icon:'document',run:()=>openTab('brief')},
  {name:'Open working notes',hint:'Editor',icon:'code',run:()=>openTab('notes')},
  {name:'Browse agents',hint:'Library',icon:'agent',run:()=>openTab('agents')},
  {name:'Inspect sources',hint:'Context',icon:'library',run:()=>openTab('sources')},
  {name:'New work',hint:'Create',icon:'plus',run:()=>openNew()},
  {name:'Toggle explorer',hint:'⌘ B',icon:'sidebar',run:()=>action('sidebar')},
  {name:'Toggle inspector',hint:'⌘ .',icon:'panel',run:()=>action('inspector')},
  {name:'Toggle activity',hint:'⌘ J',icon:'activity',run:()=>action('activity')}
];
function openCommands(){const dialog=document.querySelector('#command-dialog');dialog.innerHTML=`<div class="command-input-row">${icon('search',19)}<label class="sr-only" id="command-title" for="command-search">Search workspace commands</label><input id="command-search" type="search" placeholder="Where would you like to go?" autocomplete="off"><kbd>ESC</kbd></div><div id="command-results"></div><footer class="command-footer"><span>↑ ↓ to navigate</span><span>↵ to open</span></footer>`;dialog.showModal();const input=dialog.querySelector('input');let selected=0;let filtered=commands;const list=()=>{dialog.querySelector('#command-results').innerHTML=filtered.length?filtered.map((command,i)=>`<button class="command-option ${i===selected?'selected':''}" data-command="${commands.indexOf(command)}">${icon(command.icon,18)}<span>${command.name}</span><small>${command.hint}</small></button>`).join(''):'<p class="command-empty">No matching commands.</p>';};input.addEventListener('input',()=>{selected=0;filtered=commands.filter(c=>c.name.toLowerCase().includes(input.value.toLowerCase()));list();});input.addEventListener('keydown',event=>{if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();selected=filtered.length?(selected+(event.key==='ArrowDown'?1:-1)+filtered.length)%filtered.length:0;list();}if(event.key==='Enter'&&filtered[selected]){event.preventDefault();dialog.close();filtered[selected].run();}});dialog.querySelector('#command-results').addEventListener('click',event=>{const hit=event.target.closest('[data-command]');if(hit){dialog.close();commands[Number(hit.dataset.command)].run();}});list();input.focus();}
function openNew(){const dialog=document.querySelector('#new-dialog');dialog.innerHTML=`<form class="modal-form"><p class="eyebrow">A NEW PIECE OF WORK</p><h2 id="new-title">What are you working on?</h2><label for="work-name">Name your workspace</label><input id="work-name" name="name" placeholder="e.g. Supplier review" maxlength="64" required autocomplete="off"><p class="field-note">Creates a local workspace for this preview session.</p><div class="modal-actions"><button class="secondary-button" type="button" data-dismiss>Cancel</button><button class="primary-button" type="submit">Create workspace ${icon('arrowRight',14)}</button></div></form>`;dialog.querySelector('[data-dismiss]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=event=>{event.preventDefault();const name=dialog.querySelector('input').value.trim();if(!name)return;const id='custom-'+Date.now();state.customTabs[id]={name,icon:'folder'};dialog.close();openTab(id);notify('Workspace created for this session.');};dialog.showModal();dialog.querySelector('input').focus();}
function openSettings(){const dialog=document.querySelector('#settings-dialog');dialog.innerHTML=`<div class="modal-form"><p class="eyebrow">WORKSPACE PREFERENCES</p><h2 id="settings-title">Make room for the work.</h2><label for="density">Interface spacing</label><select id="density"><option ${state.density==='Comfortable'?'selected':''}>Comfortable</option><option ${state.density==='Compact'?'selected':''}>Compact</option></select><p class="field-note">Your layout preference is saved in this browser.</p><div class="shortcut-list"><span>Command menu</span><kbd>⌘ K</kbd><span>Explorer</span><kbd>⌘ B</kbd><span>Inspector</span><kbd>⌘ .</kbd><span>Activity</span><kbd>⌘ J</kbd></div><div class="modal-actions"><button class="primary-button" data-dismiss>Done ${icon('check',14)}</button></div></div>`;dialog.querySelector('select').onchange=event=>{state.density=event.target.value;preference();render();};dialog.querySelector('[data-dismiss]').onclick=()=>dialog.close();dialog.showModal();}
function exportDocument(){const text=state.active==='notes'?state.notes:'# Weekly delivery brief\n\nThree onboarding actions are complete. The source-data import remains blocked by unresolved field mapping. [1]\n\nA revised delivery date is not established in the records. [2]\n\nDecision: confirm who owns the field mapping. [3]\n\nSources: [1] Delivery register; [2] Working notes; [3] Decision log.\n\nFictional sample for the Koralli visual template.\n';const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=state.active==='notes'?'working-notes.md':'weekly-brief.md';link.click();setTimeout(()=>URL.revokeObjectURL(url),500);notify('Document exported.');}
function action(name){switch(name){case'route-preview':state.poseidon.previewed=true;render();app.querySelector('[data-action="route-preview"]')?.focus();notify('Illustrative route prepared. No model was called.');break;case'sidebar':state.sidebar=!state.sidebar;render();break;case'inspector':state.inspector=!state.inspector;render();break;case'activity':state.activity=!state.activity;render();break;case'command':openCommands();break;case'new':openNew();break;case'settings':openSettings();break;case'preview':startPreview();break;case'zoom-in':state.zoom=Math.min(1.25,Math.round((state.zoom+.1)*100)/100);render();break;case'zoom-out':state.zoom=Math.max(.65,Math.round((state.zoom-.1)*100)/100);render();break;case'fit':state.zoom=Math.min(1,Math.max(.65,((document.querySelector('.wf-canvas')?.clientWidth||830)-30)/800));render();break;case'approve':state.approved=true;render();notify('Example draft approved. Nothing has been shared.');break;case'export':exportDocument();break;case'switch-project':state.project=state.project==='Operations'?'Research':'Operations';notify(`Switched to ${state.project.toLowerCase()} workspace.`);render();break;}}

app.addEventListener('click',event=>{
  const element=event.target.closest('[data-action],[data-tab],[data-close-tab],[data-node],[data-agent],[data-source],[data-log],[data-route-priority]');if(!element)return;event.preventDefault();
  if(element.dataset.routePriority){if(!['balanced','speed','depth'].includes(element.dataset.routePriority))return;state.poseidon.priority=element.dataset.routePriority;state.poseidon.previewed=false;render();app.querySelector(`[data-route-priority="${state.poseidon.priority}"]`)?.focus();}
  else if(element.dataset.action)action(element.dataset.action);
  else if(element.dataset.tab)openTab(element.dataset.tab);
  else if(element.dataset.closeTab)closeTab(element.dataset.closeTab);
  else if(element.dataset.node){state.selectedNode=element.dataset.node;state.inspector=true;render();}
  else if(element.dataset.agent){state.selectedAgent=element.dataset.agent;state.inspector=true;openTab('agents');}
  else if(element.dataset.source!==undefined){state.selectedSource=Number(element.dataset.source);openTab('sources');}
  else if(element.dataset.log){state.activityTab=element.dataset.log;render();}
});
app.addEventListener('change',event=>{
  const field=event.target.dataset.routeField;
  const values={task:['research','analysis','review'],budget:['small','standard','extended']};
  if(!values[field]?.includes(event.target.value))return;
  state.poseidon[field]=event.target.value;state.poseidon.previewed=false;render();
  app.querySelector(`[data-route-field="${field}"]`)?.focus();
});
addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(Object.hasOwn(tabs,id))openTab(id);});
app.addEventListener('input',event=>{if(event.target.id==='notes-editor'){state.notes=event.target.value;state.dirty=true;document.querySelector('[data-note-status]').textContent='Edited in this session';document.querySelector('[data-word-count]').textContent=(state.notes.trim()?state.notes.trim().split(/\s+/).length:0)+' words';}if(event.target.id==='agent-instructions'){state.instructions[state.selectedAgent]=event.target.value;document.querySelector('[data-instruction-status]').textContent='Edited in this session';}});
document.addEventListener('keydown',event=>{if(event.metaKey||event.ctrlKey){const key=event.key.toLowerCase();const shortcuts={k:'command',b:'sidebar',j:'activity','.':'inspector'};if(shortcuts[key]&&!document.querySelector('dialog[open]')){event.preventDefault();action(shortcuts[key]);}}});
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const bounds=dialog.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)dialog.close();}}));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.preview){clearTimeout(previewTimer);state.preview=false;render();}});
render();
